----------------------------------------------------------------------
--
-- Copyright (c) 2004-2005, Andrew S. Townley
-- All rights reserved.
-- 
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions
-- are met:
-- 
--     * Redistributions of source code must retain the above
--     copyright notice, this list of conditions and the following
--     disclaimer.
-- 
--     * Redistributions in binary form must reproduce the above
--     copyright notice, this list of conditions and the following
--     disclaimer in the documentation and/or other materials provided
--     with the distribution.
-- 
--     * Neither the names Andrew Townley or Townley Enterprises,
--     Inc. nor the names of its contributors may be used to endorse
--     or promote products derived from this software without specific
--     prior written permission.  
-- 
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
-- 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
-- LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
-- FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
-- COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
-- INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
-- (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
-- HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
-- STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
-- ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
-- OF THE POSSIBILITY OF SUCH DAMAGE.
--
-- File:	bootstrap.sql
-- Created:	Mon Dec 27 14:53:38 GMT 2004
--
-- Description:
-- 	This file is used to provide bootstrap data required to allow
-- 	the system to function.
--
-- $Id: bootstrap.sql,v 1.2 2005/01/02 22:42:24 atownley Exp $
--
----------------------------------------------------------------------

insert into counter (what, val) values ('author', 0);
insert into counter (what, val) values ('publisher', 0);
insert into counter (what, val) values ('book', 0);
